//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobile_Repair_History_System_MRHS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BlockAcconut
    {
        public int ID { get; set; }
        public string UserEmail { get; set; }
        public string Status { get; set; }
        
        public string Reason { get; set; }
        public System.DateTime DateTime { get; set; }
    
        public virtual User User { get; set; }
    }
}
