//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobile_Repair_History_System_MRHS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Invoice
    {
        public int InvoiceID { get; set; }
        public string StoreEmail { get; set; }
        [Display(Name = "Repair Type")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Repair Type is required")]
        public string RepairType { get; set; }
        [Display(Name = "Price")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Price is required")]
        public double Price { get; set; }
        public string Image { get; set; }
        public System.DateTime Date { get; set; }
        [Display(Name = "UserPhoneNumber")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "User PhoneNumber is required")]
        [MinLength(10, ErrorMessage = "Minimum 10 characters required")]
        [MaxLength(10, ErrorMessage = "Maximum 10 characters required")]
        public string CustomerPhoneNumber { get; set; }
        [Display(Name = "DeviceID")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "DeviceID is required")]
        public string DeviceID { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageFile { get; set; }
        public virtual User User { get; set; }
    }
}
